const input = ['5 11',
    'baekjoononlinejudge',
    'startlink',
    'codeplus',
    'sundaycoding',
    'codingsh',
    'baekjoon',
    'codeplus',
    'codeminus',
    'startlink',
    'starlink',
    'sundaycoding',
    'codingsh',
    'codinghs',
    'sondaycoding',
    'startrink',
    'icerink']
    console.log(input.slice(0,1).split(' '))